name: Azure Web App Deploy - Full Stack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Install client and build React app
        run: |
          cd client
          npm install
          npm run build

      - name: Move client build to server
        run: |
          rm -rf server/client
          mv client/build server/client

      - name: Zip app for deployment
        run: zip -r app.zip .
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_AZURE_APP_NAME
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./app.zip
