name: Fullstack Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ubicom-chatbot-web-app
  AZURE_RESOURCE_GROUP: genai-research
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Step 3: Install and build React app
      - name: Install and build React app
        working-directory: ./client
        run: |
          npm ci
          npm run build
          # Diagnostics — we're inside ./client now
          echo "Listing contents of ./client/build (actually just ./build here):"
          ls -la build

      # Step 4: Copy React build to the server's root
      - name: Copy React build to server
        working-directory: ./
        run: |
          # Create the wwwroot directory in the root of the deployment package
          mkdir -p ./server/wwwroot
          cp -r ./client/build/* ./server/wwwroot/

      - name: List server folder before deploy
        run: ls -la ./server/wwwroot

      # Step 5: Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: npm ci --omit=dev

      - name: List ./server contents before deploy
        run: ls -la ./server

      # Step 6: Clean up build artifacts
      - name: Clean up build artifacts
        run: |
          rm -rf client/node_modules
          rm -f node_modules.tar.gz

      # Step 7: Deploy to Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./server/wwwroot
