name: Fullstack Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ubicom-chatbot-web-app
  AZURE_RESOURCE_GROUP: genai-research
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Step 3: Install and build React app
      - name: Install and build React app
        run: |
          npm install
          npm run build
        working-directory: ./client

      # Step 4: Copy React build to backend (public folder)
      - name: Copy React build to backend
        run: |
          rm -rf server/public
          mkdir -p server/public
          cp -r client/build/* server/public/

      # Step 5: Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: |
          npm install

      # Step 6: Prepare deployment package
      - name: Prepare deployment package
        run: |
          mkdir -p deploy/wwwroot  # Create directory for deployment package
          mkdir -p deploy/wwwroot/server  # Create directory for deployment package
          mkdir -p deploy/wwwroot/client  # Create directory for deployment package

          # Copy server files to the wwwroot directory
          cp -r server/* deploy/wwwroot/server

          # Copy client build files to wwwroot/client
          cp -r client/build/* deploy/wwwroot/client

          # Debug to verify the contents of deploy folder
          ls -alR deploy/wwwroot/

      #Step: Debug deploy folder
      - name: Debug deploy folder
        run: |
          echo "Checking deploy folder..."
          ls -al deploy/

      # Step 7: Zip the deploy folder to create deploy.zip
      - name: Zip the deploy folder
        run: |
          zip -r deploy.zip deploy/wwwroot
          echo "Created zip at: $(pwd)/deploy.zip"
          ls -l deploy.zip  # Confirm it's there

      - name: Check deploy package contents
        run: |
          unzip -l deploy.zip  # List contents of deploy.zip

      # Step 8: Deploy to Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy/deploy.zip  # Ensure the path is correct

