name: Fullstack Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ubicom-chatbot-web-app
  AZURE_RESOURCE_GROUP: your-resource-group
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install and build React app
      - name: Install and build React app
        run: |
          npm install
          npm run build
        working-directory: ./client

      # Copy React build to backend (public folder)
      - name: Copy React build to backend
        run: |
          rm -rf server/public
          mkdir -p server/public
          cp -r client/build/* server/public/

      # Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: |
          npm install
     
      # Prepare deployment package
      - name: Prepare deployment package
        run: |
          mkdir -p deploy/wwwroot
          cp -r server/* deploy/wwwroot/
          cp -r client/build/* deploy/wwwroot/

      # Deploy to Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip

      # Step 10: Restart Azure App Service (optional, after deployment)
      - name: Restart Azure App Service
        run: |
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group <your-resource-group>