name: Fullstack Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ubicom-chatbot-web-app
  AZURE_RESOURCE_GROUP: genai-research
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Step 3: Install and build React app
      - name: Install and build React app
        working-directory: ./client
        run: |
          npm ci
          npm run build

      # Step 4: Copy React build to server folder
      - name: Copy React build to server
        run: |
          cp -r ./client/build/* ./server/wwwroot/

      # Step 5: Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: |
          npm ci --omit=dev

      - name: Clean up build artifacts
        run: |
          rm -rf server/node_modules
          rm -rf client/node_modules
          rm -f node_modules.tar.gz

      # Step 8: Deploy to Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./server