# File: .github/workflows/workflow.yml
name: Fullstack Deploy to Azure

on: [push]
env:
  AZURE_WEBAPP_NAME: ubicom-chatbot-web-app
  AZURE_WEBAPP_PACKAGE_PATH: 'client/build'
  NODE_VERSION: '20.0'

jobs:
  build-and-deploy:
    
    name: Build and Deploy
    runs-on: windows-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and build React app
        run: |
          npm install
          npm run build
        working-directory: ./client

      - name: Copy React build to backend
        run: |
          rm -rf server/public
          mkdir -p server/public
          cp -r client/build/* server/public/

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Debug contents before deployment
        run: ls -alR ./server

      - name: 🚀 Deploy fullstack app to Azure (with retry)
        shell: pwsh
        run: |
          $maxRetries = 3
          $count = 1
          do {
            Write-Host "🔁 Attempt $count to deploy to Azure App Service..."
            try {
              & npx azure-webapps-deploy `
                --app-name "${{ env.AZURE_WEBAPP_NAME }}" `
                --publish-profile "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" `
                --package "./server"
              $success = $true
              Write-Host "✅ Deployment succeeded!"
            } catch {
              Write-Host "⚠️ Deployment failed on attempt $count"
              Start-Sleep -Seconds 15
              $count++
              $success = $false
            }
          } while (-not $success -and $count -le $maxRetries)

          if (-not $success) {
            Write-Error "❌ All deployment attempts failed."
            exit 1
          }